apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: default
  namespace: default
resources:
  - config.yaml
  - dashboard

configMapGenerator:
  - name: config
    namespace: default
    files:
      - config.yaml

patchesStrategicMerge:
  - patch-pv.yaml
