apiVersion: v1
kind: Service
metadata:
  name: tandoor
  namespace: web-at-home
  labels:
    tier: frontend
spec:
  ports:
  - port: 80
    targetPort: http
    name: http
    protocol: TCP
  - port: 8080
    targetPort: gunicorn
    name: gunicorn
    protocol: TCP
  selector:
    app: tandoor
    tier: frontend
