apiVersion: v1
kind: ConfigMap
metadata:
  name: subgen-config
  namespace: jelly
data:
  WHISPER_MODEL: "medium"
  WHISPER_THREADS: "4"
  PROCADDEDMEDIA: "True"
  PROCMEDIAONPLAY: "False"
  NAMESUBLANG: "ko"
  SKIPIFINTERNALSUBLANG: "kor"
  SKIPIFEXTERNALSUB: "True"
  JELLYFINTOKEN: "f5a88458593245aeb9a27068787ababe"
  JELLYFINSERVER: "http://jellyfin.jelly.svc.cluster.local:8096"
  WEBHOOKPORT: "9000"
  CONCURRENT_TRANSCRIPTIONS: "2"
  WORD_LEVEL_HIGHLIGHT: "False"
  DEBUG: "True"
  USE_PATH_MAPPING: "False"
  TRANSCRIBE_FOLDERS: "/Films|/TVShows"
  TRANSCRIBE_DEVICE: "cpu"
  CLEAR_VRAM_ON_COMPLETE: "True"
  MODEL_PATH: "./models"
  UPDATE: "False"
  APPEND: "False"
  USE_MODEL_PROMPT: "False"
  CUSTOM_MODEL_PROMPT: ""
  LRC_FOR_AUDIO_FILES: "True"
  CUSTOM_REGROUP: "cm_sl=84_sl=42++++++1"
  DETECT_LANGUAGE_LENGTH: "60"
  DETECT_LANGUAGE_OFFSET: "60"
  PREFERRED_AUDIO_LANGUAGES: "kor|eng|fra"
